////////////////////////////////////
// DEBUG
///////////////////////////////////

export const DEBUG_VALUE_UPDATED = 'DEBUG_VALUE_UPDATED'
export const HOTKEY_PRESSED = 'HOTKEY_PRESSED' // TODO hotkey pressed is a generic event - does a middleware do this transformation, or reducer?
export const CAMERA_PRESETS_LEARN_TOGGLED = 'CAMERA_PRESETS_LEARN_TOGGLED'
export const SAVE_CAMERA_HOTKEY = 'SAVE_CAMERA_HOTKEY'
export const LOAD_CAMERA_HOTKEY = 'LOAD_CAMERA_HOTKEY'

export const GARDEN_GENERATE_PLANT_PARAMS = 'GARDEN_GENERATE_PLANT_PARAMS'
export const GARDEN_UPDATE_PLANT_POSITION = 'GARDEN_UPDATE_PLANT_POSITION'

export const CAMERA_UPDATE_ROTATION_DELTA = 'CAMERA_UPDATE_ROTATION_DELTA'
export const CAMERA_UPDATE_DOLLY_DELTA = 'CAMERA_UPDATE_DOLLY_DELTA'






export const CAMERA_CONTROLS_RESET = 'CAMERA_CONTROLS_RESET'
export const GARDEN_PRESET_MODE_TOGGLED = 'GARDEN_PRESET_MODE_TOGGLED'
export const ADD_NEW_GARDEN_PRESET = 'ADD_NEW_GARDEN_PRESET'
export const LOAD_GARDEN_FROM_SELECTED_PRESET = 'LOAD_GARDEN_FROM_SELECTED_PRESET'
export const SAVE_GARDEN_TO_SELECTED_PRESET = 'SAVE_GARDEN_TO_SELECTED_PRESET'
export const GARDEN_PRESET_MODE_SAVE_NEXT_PRESET_TOGGLED = 'GARDEN_PRESET_MODE_SAVE_NEXT_PRESET_TOGGLED'
export const SAVE_GARDEN_TO_PRESET_FILE = 'SAVE_GARDEN_TO_PRESET_FILE'
export const LOAD_GARDEN_FROM_PRESET_FILE = 'LOAD_GARDEN_FROM_PRESET_FILE'


export const GENERATE_NEW_PLANTS_TEXTURE_STYLES_TOGGLE = 'GENERATE_NEW_PLANTS_TEXTURE_STYLES_TOGGLE'
export const AUDIO_ANALYSIS_CAN_UPDATE_CAMERA_TOGGLE = 'AUDIO_ANALYSIS_CAN_UPDATE_CAMERA_TOGGLE'
export const XBOX_CONTROLLER_SELECTION_TOGGLED = 'XBOX_CONTROLLER_SELECTION_TOGGLED'
export const SET_SAME_SHADER_FOR_ALL_PLANTS = 'SET_SAME_SHADER_FOR_ALL_PLANTS'
export const RESET_SHADERS_TO_INITIAL_SHADER_FOR_ALL_PLANTS = 'RESET_SHADERS_TO_INITIAL_SHADER_FOR_ALL_PLANTS'
export const AUDIO_ANALYSIS_CAN_UPDATE_CAMERA_Y_TOGGLE = 'AUDIO_ANALYSIS_CAN_UPDATE_CAMERA_Y_TOGGLE'
export const DEBUGGER_PAUSE = 'DEBUGGER_PAUSE'
export const TOGGLE_DAT_GUI = 'TOGGLE_DAT_GUI'
export const EXPORT_STL = 'EXPORT_STL'


// events.SAVE_GARDEN_TO_PRESET_FILE = 'SAVE_GARDEN_TO_PRESET_FILE'
// events.LOAD_GARDEN_FROM_PRESET_FILE = 'LOAD_GARDEN_FROM_PRESET_FILE'
// events.GENERATE_NEW_RANDOM_GARDEN = 'GENERATE_NEW_RANDOM_GARDEN'
// events.GENERATE_NEW_PLANTS_TEXTURE_STYLES_TOGGLE = 'GENERATE_NEW_PLANTS_TEXTURE_STYLES_TOGGLE'
// events.AUDIO_ANALYSIS_CAN_UPDATE_CAMERA_TOGGLE = 'AUDIO_ANALYSIS_CAN_UPDATE_CAMERA_TOGGLE'
// events.CAMERA_PRESETS_LEARN_TOGGLED = 'CAMERA_PRESETS_LEARN_TOGGLED'
// events.XBOX_CONTROLLER_SELECTION_TOGGLED = 'XBOX_CONTROLLER_SELECTION_TOGGLED'
// events.CAMERA_PRESET_LEARN = 'CAMERA_PRESET_LEARN'
// events.CAMERA_PRESET_TRIGGER = 'CAMERA_PRESET_TRIGGER'
// events.SET_SAME_SHADER_FOR_ALL_PLANTS = 'SET_SAME_SHADER_FOR_ALL_PLANTS'
// events.RESET_SHADERS_TO_INITIAL_SHADER_FOR_ALL_PLANTS = 'RESET_SHADERS_TO_INITIAL_SHADER_FOR_ALL_PLANTS'
// events.CAMERA_CONTROLS_RESET = 'CAMERA_CONTROLS_RESET'
// events.GARDEN_PRESET_MODE_TOGGLED = 'GARDEN_PRESET_MODE_TOGGLED'
// events.ADD_NEW_GARDEN_PRESET = 'ADD_NEW_GARDEN_PRESET'
// events.LOAD_GARDEN_FROM_SELECTED_PRESET = 'LOAD_GARDEN_FROM_SELECTED_PRESET'
// events.SAVE_GARDEN_TO_SELECTED_PRESET = 'SAVE_GARDEN_TO_SELECTED_PRESET'
// events.GARDEN_PRESET_MODE_SAVE_NEXT_PRESET_TOGGLED = 'GARDEN_PRESET_MODE_SAVE_NEXT_PRESET_TOGGLED'
