
//TODO naming scheme

// server API actions
export const REQUEST_INITIAL_DATA = 'REQUEST_INITIAL_DATA'
export const REQUEST_LAMPS = 'REQUEST_LAMPS'
export const REQUEST_GROUPS = 'REQUEST_GROUPS'
export const REQUEST_FEATURES_TYPES = 'REQUEST_FEATURES_TYPES'
export const REQUEST_GENERATOR_TYPES = 'REQUEST_GENERATOR_TYPES'
export const REQUEST_GENERATORS_LIST = 'REQUEST_GENERATORS_LIST'
export const REQUEST_SCENE_LIST = 'REQUEST_SCENE_LIST'
export const REQUEST_LOAD_SCENE = 'REQUEST_LOAD_SCENE'
export const REQUEST_SAVE_SCENE = 'REQUEST_SAVE_SCENE'
export const REQUEST_PRESET_PLAYER_PAUSE = 'REQUEST_PRESET_PLAYER_PAUSE'
export const REQUEST_PRESET_PLAYER_RESUME = 'REQUEST_PRESET_PLAYER_RESUME'

export const UPDATE_INITIAL_DATA = 'UPDATE_INITIAL_DATA'
export const UPDATE_LOAD_SCENE = 'UPDATE_LOAD_SCENE'
export const UPDATE_ENTITY_LAMPS = 'UPDATE_ENTITY_LAMPS'
export const UPDATE_ENTITY_GROUPS = 'UPDATE_ENTITY_GROUPS'
export const UPDATE_ENTITY_FEATURES_TYPES = 'UPDATE_ENTITY_FEATURES_TYPES'
export const UPDATE_ENTITY_GENERATOR_TYPES = 'UPDATE_ENTITY_GENERATOR_TYPES'
export const UPDATE_ENTITY_GENERATORS = 'UPDATE_ENTITY_GENERATORS'
export const UPDATE_ENTITY_SCENES = 'UPDATE_ENTITY_SCENES'
export const UPDATE_GENERATOR_PARAMS = 'UPDATE_GENERATOR_PARAMS'
export const UPDATE_PRESET_PLAYER_STATE_CHANGED = 'UPDATE_PRESET_PLAYER_STATE_CHANGED'

export const ADD_LAMP_TO_GROUP_REQUEST = 'ADD_LAMP_TO_GROUP_REQUEST'

export const REQUEST_GENERATOR_PARAMETER_UPDATE = 'REQUEST_GENERATOR_PARAMETER_UPDATE'
export const REQUEST_GENERATOR_PARAMS = 'REQUEST_GENERATOR_PARAMS'

// groups-lamps canvas shared actions
export const SELECT_LAMP = 'SELECT_LAMP'
export const UPDATE_LAMP = 'UPDATE_LAMP'

// patching actions
export const PATCHING_CONNECT_START = 'PATCHING_CONNECT_START'
export const PATCHING_CONNECT_SELECT = 'PATCHING_CONNECT_SELECT'
export const PATCHING_CONNECT_END = 'PATCHING_CONNECT_END'
export const PATCHING_CONNECT_END_AND_CLEAR = 'PATCHING_CONNECT_END_AND_CLEAR'
export const PATCHING_MODE_UPDATE = 'PATCHING_MODE_UPDATE'
export const PATCHING_MOUSE_UPDATE = 'PATCHING_MOUSE_UPDATE'

// patching modes - TODO these are enum constants, not really actions
export const PATCHING_MODE_MOVE = 'PATCHING_MODE_MOVE'
export const PATCHING_MODE_CONNECT = 'PATCHING_MODE_CONNECT'
export const PATCHING_MODE_DISCONNECT = 'PATCHING_MODE_DISCONNECT'

// content actions

export const CONTENT_GENERATOR_ATTACH = 'CONTENT_GENERATOR_ATTACH'
export const CONTENT_GENERATOR_DETACH = 'CONTENT_GENERATOR_DETACH'

export const UPDATE_LIVE_PREVIEW = 'UPDATE_LIVE_PREVIEW'
export const CONTENT_LIVE_PREVIEW_START = 'CONTENT_LIVE_PREVIEW_START'
export const CONTENT_LIVE_PREVIEW_STOP = 'CONTENT_LIVE_PREVIEW_STOP'


export const CONTENT_LIST_ITEM_GROUP_SELECTED = 'CONTENT_LIST_ITEM_GROUP_SELECTED'
export const CONTENT_LIST_ITEM_GENERATOR_SELECTED = 'CONTENT_LIST_ITEM_GENERATOR_SELECTED'
export const CONTENT_PANE_SET_VISIBILITY_LEFT_OVERLAY = 'CONTENT_PANE_SET_VISIBILITY_LEFT_OVERLAY'
export const CONTENT_PANE_SET_VISIBILITY_GENERATOR_PARAMS = 'CONTENT_PANE_SET_VISIBILITY_GENERATOR_PARAMS'
export const CONTENT_FEATURE_SELECTED = 'CONTENT_FEATURE_SELECTED'
export const CONTENT_DRAGGING = 'CONTENT_DRAGGING'
